name: Build docs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3 # https://github.com/peaceiris/actions-gh-pages
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        force_orphan: true
        exclude_assets: '.github,openapi,.redocly.yaml,LICENSE,README.md,make.sh'
        cname: docs.api.jizt.it
